### ISSUE TITLE
Trouble running last cmake command line

### ISSUE THREAD

**Issue by JoelRV** [jfnavarro/st_viewer#18] opened 2018-01-26 14:58 UTC
Greetings,

I have been having trouble to cmake the final build of the st_viewer on ubuntu 16.04.

I followed your readme and install all prerequisites, but I systematically fall back on this error:

```
$cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_PREFIX_PATH="/home/joelrv/Qt5.9.4/5.9.4/gcc_64;/home/joelrv/Desktop/st_viewer/dependencies/qcustomplot;/home/joelrv/Desktop/st_viewer/dependencies/armadillo-8.300.3"  ../st_viewer
-- 
-- -------------------------------------------------------------------------------
-- Building Spatial Transcriptomics Research Viewer .....
-- Change a configuration variable with: cmake -D<Variable>=<Value>
-- CMAKE_INSTALL_PREFIX = /usr/local
-- CMAKE_BUILD_TYPE = Release
-- CMAKE_PREFIX_PATH = /home/joelrv/Qt5.9.4/5.9.4/gcc_64;/home/joelrv/Desktop/st_viewer/dependencies/qcustomplot;/home/joelrv/Desktop/st_viewer/dependencies/armadillo-8.300.3
-- TARGET_ARCH = 
-- VERSION = 0.7.0
-- CONFIGURATION FILE = /home/joelrv/Desktop/st_viewer/git/st_viewer/assets/stviewer.conf
-- -------------------------------------------------------------------------------
-- 
-- Building a release version...
-- Found R include dir: /usr/share/R/include
-- Found R libraries: /usr/lib/R/lib/libR.so
-- Found R lapack libraries: /usr/lib/R/lib/libRlapack.so
-- Found R blas libraries: /usr/lib/R/lib/libRblas.so
CMake Warning (dev) in cmake/FindR.cmake:
  A logical block opening on the line

    /home/joelrv/Desktop/st_viewer/git/st_viewer/cmake/FindR.cmake:157 (if)

  closes on the line

    /home/joelrv/Desktop/st_viewer/git/st_viewer/cmake/FindR.cmake:159 (endif)

  with mis-matching arguments.
Call Stack (most recent call first):
  src/CMakeLists.txt:54 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/FindR.cmake:160 (set):
  set called with incorrect number of arguments
Call Stack (most recent call first):
  src/CMakeLists.txt:54 (find_package)


-- Found Rcpp: /home/joelrv/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include
-- Found RInside: /home/joelrv/R/x86_64-pc-linux-gnu-library/3.4/RInside/include
-- Found RInside libraries: -L/home/joelrv/R/x86_64-pc-linux-gnu-library/3.4/RInside/lib -lRInside -Wl,-rpath,/home/joelrv/R/x86_64-pc-linux-gnu-library/3.4/RInside/lib
-- Found RcppArmadillo: /home/joelrv/R/x86_64-pc-linux-gnu-library/3.4/RcppArmadillo/include
-- Configuring incomplete, errors occurred!
See also "/home/joelrv/Desktop/st_viewer/git/st_viewer_build/CMakeFiles/CMakeOutput.log".
```

I even tried installing it on a fresh Vagrant virtualbox, but I keep falling back to the same error. Unless I am missing some obvious stuff, I am stuck at this stage.

Do you have an idea of what is going wrong? If you need logfiles (
[CMakeOutput.log](https://github.com/jfnavarro/st_viewer/files/1668126/CMakeOutput.log)) or other, let me know!

Thanks!

**Comment by jfnavarro** [comment] 2018-01-26 15:51
Can you try now?

**Comment by JoelRV** [comment] 2018-01-26 16:01
Great!
After pulling, the cmake command now builds the files (while still indicating that CMake warning in RindR.cmake).

But now when proceeding to the "make -j4" command line, it stops at

```
[ 68%] Built target viewRenderer
[ 68%] Built target model
[ 68%] Built target viewPages
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2
```

The whole output can be found here (
[make.log](https://github.com/jfnavarro/st_viewer/files/1668302/make.log)).

In any case, thank you for your fast response, I really appreciate it Mr. Navarro.

**Comment by jfnavarro** [comment] 2018-01-26 16:13
Are you using CMake 3.7.2 or older?

**Comment by JoelRV** [comment] 2018-01-26 17:19
For Cmake : 

```
$cmake --version
cmake version 3.7.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

For the rest, I am using:
Qt 5.9.4
Armadillo 8.300.3
Qcustomplot 1.3.2
Lastest version of Ubuntu and R packages listed in the readme

**Comment by jfnavarro** [comment] 2018-01-28 16:09
Okay that is odd. I tested it in a Fedora machine and it worked fine. Maybe you can try a newer version of CMake or Qt 5.9.3 (Although, I doubt this is causing problems). I will try to build it on an Ubuntu virtual machine when I find some time this week.

**Comment by JoelRV** [comment] 2018-01-28 17:17
Thanks for trying. I'll do the same with my windows machine at home to see if it is a problem specific to my machine in the Lab.

**Comment by JoelRV** [comment] 2018-01-28 20:27
Update:

So I ran I fresh Ubuntu 16.4 installation on a VM at my home machine.
After updating through `sudo apt-get` and getting all dependencies at the respective versions, I ran the cmake command.

Observations:

1. I had to add a parameter to the comand line, i.e. `cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_PREFIX_PATH="/home/joelrv/Qt5.10.0/5.10.0/gcc_64;/home/joelrv/st_viewer/dependecies/qcustomplot;/home/joelrv/st_viewer/dependecies/armadillo-8.300.3" -DLIBR_LAPACK_LIBRARY="/usr/lib/lapack/liblapack.so.3.6.0" ../st_viewer`
Because it wouldn't set the LIBR_LAPACK_LIBRARY variable.
Optionaly, one can go modify the st_viwer/cmake/FindR.cmake file, i.e.
`112: find_library(LIBR_LAPACK_LIBRARY NAMES Rlapack`
to
`112: find_library(LIBR_LAPACK_LIBRARY NAMES Rlapack lapack`

2. After running make, sadly the same error pops up:
```
[ 18%] Built target data_autogen
[ 19%] Building CXX object src/data/CMakeFiles/data.dir/STData.cpp.o
In file included from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadilloForward.h:28:0,
                 from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadillo.h:31,
                 from /home/joelrv/st_viewer/git/st_viewer/src/math/RInterface.h:8,
                 from /home/joelrv/st_viewer/git/st_viewer/src/data/STData.cpp:7:
/usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadilloConfig.h:83:0: error: "ARMA_COUT_STREAM" redefined
 #define ARMA_COUT_STREAM Rcpp::Rcout
 ^
In file included from /home/joelrv/st_viewer/dependecies/armadillo-8.300.3/include/armadillo:52:0,
                 from /home/joelrv/st_viewer/git/st_viewer/src/data/STData.h:16,
                 from /home/joelrv/st_viewer/git/st_viewer/src/data/STData.cpp:1:
/home/joelrv/st_viewer/dependecies/armadillo-8.300.3/include/armadillo_bits/config.hpp:173:0: note: this is the location of the previous definition
     #define ARMA_COUT_STREAM std::cout
 ^
In file included from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadilloForward.h:28:0,
                 from /usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadillo.h:31,
                 from /home/joelrv/st_viewer/git/st_viewer/src/math/RInterface.h:8,
                 from /home/joelrv/st_viewer/git/st_viewer/src/data/STData.cpp:7:
/usr/local/lib/R/site-library/RcppArmadillo/include/RcppArmadilloConfig.h:86:0: error: "ARMA_CERR_STREAM" redefined
 #define ARMA_CERR_STREAM Rcpp::Rcerr
 ^
In file included from /home/joelrv/st_viewer/dependecies/armadillo-8.300.3/include/armadillo:52:0,
                 from /home/joelrv/st_viewer/git/st_viewer/src/data/STData.h:16,
                 from /home/joelrv/st_viewer/git/st_viewer/src/data/STData.cpp:1:
/home/joelrv/st_viewer/dependecies/armadillo-8.300.3/include/armadillo_bits/config.hpp:182:0: note: this is the location of the previous definition
     #define ARMA_CERR_STREAM std::cerr
 ^
src/data/CMakeFiles/data.dir/build.make:182: recipe for target 'src/data/CMakeFiles/data.dir/STData.cpp.o' failed
make[2]: *** [src/data/CMakeFiles/data.dir/STData.cpp.o] Error 1
CMakeFiles/Makefile2:465: recipe for target 'src/data/CMakeFiles/data.dir/all' failed
make[1]: *** [src/data/CMakeFiles/data.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
```

3. As suggest, I tried running Qt 5.9.3 and cmake 3.10.2 in all possible combinations, but the same error mentioned in point 2 is reproduced.

I will try to run it on a Fedora VM tomorrow as an potential workaround.

**Comment by JoelRV** [comment] 2018-01-29 14:29
UPDATE 2:
So today I took some time to run a Fedora 27 VM.

I fell back on the same error ([makelog_fedora.txt](https://github.com/jfnavarro/st_viewer/files/1673889/makelog_fedora.txt))

This leads me to apply Occam's razor and work under the assumption that I am missing some crucial command line.

If possible and at your convenience, would it be possible to share a file containing al the command line inputs you use when starting on a fresh VM and installing st_viewer? (sh and R inputs etc)

**Comment by jfnavarro** [comment] 2018-01-29 14:38
That is a different error....and it seems to be related with Armadillo...how did you build it? Could you try and older version? Yes, sure share that.

**Comment by JoelRV** [comment] 2018-01-29 14:59
Well here is a summary of the relevant command line history as well as the last cmake output.
[fedora_history.txt](https://github.com/jfnavarro/st_viewer/files/1673996/fedora_history.txt)
As you can see there was a lot of back and forth as to install all libraries necessary for the individual R packages.

If you see something crucial missing, please feel free to point it out.

**Comment by jfnavarro** [comment] 2018-01-29 15:17
It seems like you install cmake from the source and then with yum? I would also try an older version of armadillo.

**Comment by JoelRV** [comment] 2018-01-29 20:22
In the meantime a went home and tried the same process on my home windows machine.

Indeed I had run yum with cmake. But since I compiled cmake 3.7.2 later one, the right bin was linked, which I checked before running the cmake command.

I tried to run it again with a compiled version of armadillo 7.800.1, but the same error appears ([armadillo_7_800_1.txt](https://github.com/jfnavarro/st_viewer/files/1675073/armadillo_7_800_1.txt)).

Would you happen to have the history of the commands you ran on your side when you tried it on your Fedora VM?

**Comment by JoelRV** [comment] 2018-01-30 12:59
Good news!

After digging around and tracing back the errors and cpp files, I seem to have found the most likely culprit:
When using `biocLite("RcppArmadillo")` it would install the latest release that was using armadillo 8.200.1. 
By using `devtools`, I forced R to install the 7.800.2 version of RccpArmadillo.

After this I reran
`/home/joelrv/Desktop/st_viewer/dependencies/cmake-3.7.2/bin/cmake -DCMAKE_BUILD_TYPE="Release" -DCMAKE_PREFIX_PATH="/home/joelrv/Qt/5.10.0/gcc_64;/home/joelrv/Desktop/st_viewer/dependencies/qcustomplot;/home/joelrv/Desktop/st_viewer/dependencies/armadillo-7.800.1" ../st_viewer`

And `make` and `make install` worked without errors.

Also note that when I tried to run `STViewer` I would get some shared libraries errors, i.e. `STViewer: error while loading shared libraries: libQt5Charts.so.5: cannot open shared object file: No such file or directory`

I circumbeted that problem by adding `export LD_LIBRARY_PATH=/usr/lib/R/lib/:/home/joelrv/Qt/5.10.0/gcc_64/lib:` to my .bashrc.

In any case the software is up and running and I am currently playing around with some of our samples.

Thank you very much for taking time to help our in this matter Mr. Navarro!

**Comment by jfnavarro** [comment] 2018-01-30 13:10
That makes sense as everything pointed at that the error was being caused by Armadillo. I have just tested and built it on an ubuntu machine with no problems. Good work figuring this out! 

Yeah, I think you would need that if you run the ST Viewer from the installed location. If you run it from the build folder then it should be fine. 

So I can can close this issue?

**Comment by JoelRV** [comment] 2018-01-30 15:17
Sure thing, consider the issue closed. Thanks for your work and app ;)

**Closed** 2018-01-30 15:21 UTC
